### ISSUE TITLE
Human atlas not available in notebook?

### ISSUE THREAD

**Issue by Gibbsdavidl** [calico/scnym#11]
Hi there,

Could the scnym_atlas_transfer notebook in the README be updated to include the human atlas?

Thanks!

ValueError                                Traceback (most recent call last)
<ipython-input-8-92fe1e31ca84> in <module>()
      5 if ATLAS2USE not in CELL_ATLASES.keys():
      6   msg = f'{ATLAS2USE} is not available in the cell atlas directory.'
----> 7   raise ValueError(msg)

ValueError: human is not available in the cell atlas directory.

**Comment by jacobkimmel** [comment]
Hi David,

Thanks for your interest!

We removed the human atlas after several users had poor experiences with the data. The annotations in the HCL appear to contain some errors, and we haven’t worked directly with the data ourselves.
For human data, I’d suggest using a tissue specific dataset from the same tissue as your sample as a reference. Happy to help point you to a relevant set if you don’t know of one.

All the best,
Jacob

**Comment by Gibbsdavidl** [comment]
Thanks for the feedback!
Any thoughts on training data for esophagus and stomach?

Possibly this: https://pubmed.ncbi.nlm.nih.gov/31892341/

Thanks much!
-dave

**Comment by jacobkimmel** [comment]
Sadly I haven't seen great human data for GI tissues yet.
The best esophagus data I've seen is in: https://www.nature.com/articles/s41467-018-06796-9

For stomach, the HCL may still be your best bet.
A [link to our pre-processed version is here](https://storage.googleapis.com/calico-website-scnym-storage/reference_data/human_guo_2020_human_cell_landscape_adult.h5ad). 
I'd subset to the GI tissues before training and double check labels against some known biology too.

Happy to help if you run into issues.

**Comment by Gibbsdavidl** [comment]
Great, thanks!
Consider this issue **closed**!
