### ISSUE TITLE
domain_groupby argument missing

### ISSUE THREAD

**Issue by MariekeL** [calico/scnym#12]
Thank you for developing scNym. I've been using it to infer cell populations between datasets. However, after going over your guidelines on how to use scNym I noticed that the argument domain_groupby seems to be missing from the scnym_api function. As such, I'm wondering which steps I need to take in order to be able to run scNym using multiple domains.
I've been using the scNym version 0.3.0 in python 3.8.5.

**Comment by jacobkimmel** [comment]
Hi @MariekeL, thanks for your interest! This looks like a bad PR on my end. It will be fixed by EOD and I'll tag you. Thanks for the heads up!

**Comment by jacobkimmel** [comment]
@MariekeL : For now, you can use multidomain training with the following edit to the model config file.

```python
config_name = "no_new_identity" # or other valid config
config = scnym.api.CONFIGS[config_name]
config["domain_groupby"] = "your_domain_column"

scnym.api.scnym_api(
  adata=adata, groupby=groupby, out_path=out_path, config=config,
)
```

**Comment by jacobkimmel** [comment]
@MariekeL Apologies for the trouble. This should be fixed now if you update your Github checkout to `master` or `pip install --upgrade scnym`. Double check that your final installed version now reads `0.3.1`.
